<section class="mbr-section mbr-section__container article" id="header3-14" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h3 class="mbr-section-title display-2" style="color: black">disponibilité</h3>
            </div>
        </div>
    </div>
</section>
