<section class="mbr-section mbr-section-md-padding mbr-footer footer2" id="contacts2-a" style="background-color: rgb(46, 46, 46); padding-top: 30px; padding-bottom: 30px;">
    <div class="container">
        <div class="row">
            <div class="mbr-footer-content col-xs-12 col-md-3">
                <p><strong>Adresse</strong><br>
                    13 Rue des Fusillés<br>
                    Vereilles<br>
                    34260 La Tour-sur-Orb<br>
                    <br><strong>Nos points de contacts</strong><br>
                    Email: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; info@LaTrêve.eu<br>
                    Téléphone: +33 (0)4 67 97 14 17<br>
                    Mobile: &nbsp; &nbsp; &nbsp; &nbsp;+33 (0)6 86 14 91 01<br><br>
                    Diégo: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;+32 (0)475 79 73 62<br>
                    Ella: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; +32 (0)473 33 26 06
                </p>
            </div>
            <div class="mbr-footer-content col-xs-12 col-md-3"><p class="mbr-contacts__text"><strong>Links</strong></p>
                <ul><li><a href="http://camping.sieste.pagesperso-orange.fr/campingNL.html" target="_blank">Camping La Siëste</a></li>
                    <li><a href="http://www.herault-tourisme.com" target="_blank">Herault tourisme</a></li>
                </ul>
            </div>
            <div class="col-xs-12 col-md-6">
                <div class="mbr-map"><iframe frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyA0Dx_boXQiwvdz8sJHoYeZNVTdoWONYkU&amp;q=place_id:ChIJG751Sax-sRIR31rkN25r7GE" allowfullscreen=""></iframe></div>
            </div>
        </div>
    </div>
</section>

<section class="mbr-section mbr-section-md-padding" id="social-buttons4-c" style="background-color: rgb(46, 46, 46); padding-top: 30px; padding-bottom: 30px;">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-xs-center">
                <h3 class="mbr-section-title display-2">visitez nous sur</h3>
                <div>
                    <a class="btn btn-social" title="Facebook" target="_blank" href="https://www.facebook.com/LaTreveVereilles/?ref=bookmarks"><i class="socicon socicon-facebook"></i></a>
                    <a class="btn btn-social" title="Google+" target="_blank" href="https://plus.google.com/110153999119111091426"><i class="socicon socicon-googleplus"></i></a>
                </div>
            </div>
        </div>
    </div>
</section>
