<section id="menu-0">
<nav class="navbar navbar-dropdown bg-color transparent navbar-fixed-top">
    <div class="container">

        <div class="mbr-table">
            <div class="mbr-table-cell">
                <div class="navbar-brand"><a href="index.php" class="navbar-logo"><img src="../assets/images/logo2-464x128.png" alt="Bienvenue à La Trêve"></a></div>
            </div>
            <div class="mbr-table-cell">

                <button class="navbar-toggler pull-xs-right hidden-md-up" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                    <div class="hamburger-icon"></div>
                </button>
                <ul class="nav-dropdown collapse pull-xs-right nav navbar-nav navbar-toggleable-sm" id="exCollapsingNavbar">
                    <li class="nav-item"><a class="nav-link link" href="index.php#overview">ACCEUIL</a></li>
                    <li class="nav-item"><a class="nav-link link" href="index.php#domain">PROPRIETE</a></li>
                    <li class="nav-item"><a class="nav-link link" href="index.php#accomodation">RESIDENCE</a></li>
                    <li class="nav-item"><a class="nav-link link" href="index.php#environment">ALENTOURS</a></li>
                    <li class="nav-item"><a class="nav-link link" href="index.php#contactus">CONTACT</a></li>
                    <li class="nav-item dropdown"><a class="nav-link link dropdown-toggle" data-toggle="dropdown-submenu" href="index.php/" aria-expanded="false">FR</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="../nl/index.php">Nederlands</a>
                            <a class="dropdown-item" href="../en/index.php">English</a>
                        </div>
                    </li>
                </ul>
                <button hidden="" class="navbar-toggler navbar-close" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
                    <div class="close-icon"></div>
                </button>

            </div>
        </div>
    </div>
</nav>
</section>
