<section class="mbr-section article mbr-section__container" id="content1-y" style="background-color: rgb(255, 255, 255); padding-top: 20px; padding-bottom: 20px;">
    <div class="container">
        <div class="row">
            <div class="col-xs-1 col-md-2 col-xl-3 lead"></div>
            <div class="col-xs-10 col-md-8 col-xl-6 lead">
				<p>
				<iframe src="https://www.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showTabs=0&amp;showCalendars=0&amp;showTz=0&amp;height=250&amp;wkst=7&amp;bgcolor=%23FFFFFF&amp;src=prhrijs0j49dnfau1lphn60his%40group.calendar.google.com&amp;color=%23711616&amp;ctz=Europe%2FBrussels" style=" border:solid 1px #777 " width="100%" height="250" frameborder="0" scrolling="no"></iframe>
				</p>
				<p>Contacteer ons voor informatie over prijzen en boekingen.</p>
			</div>
            <div class="col-xs-1 col-md-2 col-xl-3 lead"></div>
        </div>
    </div>
</section>
